### ISSUE TITLE
If you don't configure sonar.tfvc.collectionuri and use TFS 2015 or TFVC, the plugin silently fails

### ISSUE THREAD

**Issue by fmallet** [lg2de/sonar-scm-tfvc#22]
Install the TFVC SCM plugin and run a build + analysis, but do not set sonar.tfvc.collectionuri.
Assuming TFS 2015 is used, the plugin will fail with some warnings that are not very helpful in understanding the problem. I propose we improve the error message to clearly state that a possible cause for this is not setting sonar.tfvc.collectionuri

13:44:30.789 WARN - Missing blame information for the following files:
13:44:30.790 WARN - \* C:/agent/_work/4/s/main/ClassLibrary1/Class1.cs
13:44:30.790 WARN - \* C:/agent/_work/4/s/main/ClassLibrary1/Properties/AssemblyInfo.cs
13:44:30.790 WARN - This may lead to missing/broken features in SonarQube

**Comment by lg2de** [comment]
Hey @fmallet, today I've completed testing configuration validation in #53.
Do you like to test the [preview build](https://ci.appveyor.com/api/buildjobs/vs6tfcww4yge5nso/artifacts/sonar-scm-tfvc-plugin%2Ftarget%2Fsonar-scm-tfvc-plugin-2.3-SNAPSHOT.jar)?
