### ISSUE TITLE
The annotations text is too long when using windows live IDs

### ISSUE THREAD

**Issue by fmallet** [lg2de/sonar-scm-tfvc#23]
1. Use VSTS and use a live ID to connect
2. Use the TFVC SCM plugin

Actual: the username strings are "windows live id/ someuser@outlook.com" - this gets truncated to "window..." (see atached picture)

Expected: do not use the "windows live id" prefix

**Comment by fmallet** [comment]
![image](https://cloud.githubusercontent.com/assets/548729/14879039/2daa8810-0d27-11e6-98e4-fdf4697fc07a.png)

**Comment by lg2de** [comment]
Hey @fmallet , would you like to test the pull request build from [appveyor](https://ci.appveyor.com/api/buildjobs/h32po7kr4jbilkvk/artifacts/sonar-scm-tfvc-plugin%2Ftarget%2Fsonar-scm-tfvc-plugin-2.3-SNAPSHOT.jar)?
