### ISSUE TITLE
Remove VS/TFS SKU dependency and make TFVc plugin depend only on TFS OM SKU

### ISSUE THREAD

**Issue by fmallet** [lg2de/sonar-scm-tfvc#25]
Currently, TFVC Plugin fails if Visual Studio of Team Foundation Server SKU is not installed. This ticket is to track making TFVC plugin work with only TFS OM SKU.

Some more related info :

Dinesh Bolkensteyn added a comment - 47 minutes ago - edited
Hello Vishnupriyan Radhamanalan, Mathew Aniyan
Just a quick message to let you know (if it was not the case) that the TFS 2015 Object Model now ships as a NuGet package and its license allows it to be redistributed. See http://blogs.msdn.com/b/buckh/archive/2015/08/10/nuget-packages-for-tfs-and-visual-studio-online-net-client-object-model.aspx

Vishnupriyan Radhamanalan added a comment - 27 minutes ago
Thanks Dinesh. 
Yes, we discussed about taking dependency on the TFS Object Model. However, we want to understand the compatibility between different versions - 2013, 2015. So, We will create a separate ticket to work on this.

**Comment by lg2de** [comment]
With #48 I'm planning to switch to Microsoft.TeamFoundationServer.ExtendedClient package, which should solve this issue.

**Comment by lg2de** [comment]
Fixed with #48.
