### ISSUE TITLE
TFVC SCM auto-detection does not work when using server workspaces (such as from within TFS 2013 Builds)

### ISSUE THREAD

**Issue by dbolkensteyn** [lg2de/sonar-scm-tfvc#26]
It seems that no hidden `$tf` folder gets created by TFS 2013 in its `Build` directory. Therefore, the SCM detection fails.

However, when `/d:sonar.scm.provider=tfvc` is explicitly set, the TFVC SCM plugin is able to successfully import SCM data.

The TFVC SCM plugin should probably rely on TFVC APIs to determine whether or not a folder is part of a workspace - rather than rely on the presence of this `$tf` hidden folder.

Ticket migrated from https://jira.sonarsource.com/browse/SONARMSBRU-219

**Comment by lg2de** [comment]
I guess, this is really relevant anymore. The current build system is always using local workspace.

So, I'm going to close this (quite old) issue.
Feel free to reopen if still an issue for you.
