### ISSUE TITLE
Error on TFS 2017 update 1 on prem

### ISSUE THREAD

**Issue by dumians** [lg2de/sonar-scm-tfvc#35]
Hi 
I am using the plugin with sonra 6.3 and tfs 2017 update 1 on prem. i got following error

ERROR: Unable to TFS annotate the project which raised the following authentication exception: TF30063: You are not authorized to access .

Regards, 
Johannes

**Comment by wilsade** [comment]
Same here

**Comment by bogoreser** [comment]
Hi,
I just had the same issue, but as we tried to solve it, it was a missing permission of my used SonarQube user who didn't have access to the project key on the server. The error message was not correct, stating it is an authentication problem on the TFS side.
Perhaps it is similar to your environment.

**Comment by lg2de** [comment]
This issue is quite old and I'm unable reproduce it.
So, I going to close it for now.
Feel free to reopen if needed.
