### ISSUE TITLE
Use TFS 2015 object model instead of TFS 2013 ones

### ISSUE THREAD

**Issue by sorgeas** [lg2de/sonar-scm-tfvc#36]
I'd like to avoid installing TFS 2013 object model on TFS 2015/2017 on prem. Could you please upgrade the plugin?

**Comment by lg2de** [comment]
#48 is ongoing therefore.

**Comment by lg2de** [comment]
@sorgeas Would you like to test a [snapshot version](https://ci.appveyor.com/api/buildjobs/kbm0ae00l6060lq8/artifacts/sonar-scm-tfvc-plugin%2Ftarget%2Fsonar-scm-tfvc-plugin-2.3-SNAPSHOT.jar)?

**Comment by sorgeas** [comment]
I've setup the 2.3-SNAPSHOT on SonarQube 6.7.3.38370 to communicate with an onprem TFS 2018. 
I'm getting the following error:

`ERROR: SCM-TFVC: Unable to annotate the project which raised the following authentication exception: TF30063: You are not authorized to access https://mytfs/tfs/projectcoll.`

Could you please let me know if this version also supports TFS 2018? Should I use my domain user & password or rather a PAT?

**Comment by lg2de** [comment]
We are using always PAT to be configured at `https://[...]/admin/settings?category=scm`.

I'm glad to hear you succeeded.
So, this feature will be included in next release.
