### ISSUE TITLE
Support visual Studio 2017

### ISSUE THREAD

**Issue by wilsade** [lg2de/sonar-scm-tfvc#42]
It does not work with Visual Studio 2017.

Thanks,

**Comment by wilsade** [comment]
Hi there.
How can I make it work with Visual Studio 2017?
I am using Sonar 6.7.5.38563.
Thanks.

**Comment by lg2de** [comment]
#48 is planned for next release to solve this issue.

**Comment by lg2de** [comment]
@wilsade Would you like to test a [snapshot version](https://ci.appveyor.com/api/buildjobs/kbm0ae00l6060lq8/artifacts/sonar-scm-tfvc-plugin%2Ftarget%2Fsonar-scm-tfvc-plugin-2.3-SNAPSHOT.jar)?

**Comment by wilsade** [comment]
Hi.
I tried to use. Two issues:
1. Error message saying that there is no TFS mapped working forder for my file.
2. My antivurus bloqued SonarTfsAnnotate

**Comment by lg2de** [comment]
@wilsade 
Regarding 1) Please provided detailed log information. Are other files processed correctly? Maybe it is subsequent fault of 2).
Regarding 2) I do not know how to prevent from this. Did your antivirus identified a specific issue? Please provide more details. Would you like to check the EXE for you own with e.g. virustotal.com? Just now I checked and "SecureAge APEX" decided for "Malicious" but did not get details. All other 67 engines does not detect an issue.

**Comment by lg2de** [comment]
With the [new analysis](https://www.virustotal.com/gui/file/14d0db0f6ea662510e93eb7bd60b25a6b62f72e593ff0d399c326bba91cc2404/detection) the EXE is "green" now on virustotal.com.

**Comment by lg2de** [comment]
Fixed with #48.

**Comment by wilsade** [comment]
Hi.
Can you provide a Release so I can test it?
Thanks,

**Comment by lg2de** [comment]
I want to add more fixes before releasing a new version. 
But you can test (again) the test build linked above or this newer one:
https://ci.appveyor.com/project/lg2de/sonar-scm-tfvc/builds/27882763/artifacts
