### ISSUE TITLE
Blame information seems to be not properly retrieved for users at merges

### ISSUE THREAD

**Issue by StefanAdel** [lg2de/sonar-scm-tfvc#60]
I've got a problem / request regarding the way how the plugin does resolve the blaming / annotation for source files from the TFS. In generell it works nicely, but when resolving the blame-user for a line which came to the TFS-branch by merging from another, it always shows just the merging-user, but not the real contributor of this line of code. This causes some problems, because the merge-user is either just a generic one when auto-merging or a completely different person than the original author when doing manual merges. All issues are getting assigned to that wrong user.

Please see the attached screenshot for better understanding:
![merge-blame (1)](https://user-images.githubusercontent.com/64962699/81290455-65f86e80-9068-11ea-94cd-3b06e6742b69.png)

In this case the merge #894659 was auto-merged by a build user (TFSE-Build1), but the real user behind was Max Mustermann. SonarQube always assigns all changed lines to TFSE-Build1 while Visual Studio is able to show the real user Max when looking at source code in Visual Studio.

Is there any possibility to get the issues assigned to the real user, but not the merge-user?
If not: Is this sth. which is known / planned for future releases?

**Comment by lg2de** [comment]
Sorry for the strong delay for my comment...

You description sounds close to #24. So far I could not reproduce this issue.
Please provide further details on the used versions: SonarQube server, analyzer version, TFS/DevOps version, plugin version, ...

**Comment by StefanAdel** [comment]
hi Lukas, thanks for your answer!

It sounds somehow similar to the other issue, but I think it's not entirely the same. I don't really have those errors when branching. But when merging back it sounds pretty much like my problem. I don't get the codeline assigned to the real user, who did that change, but to the one who merged it back to the main branch. I think that's exactly what fmallet is describing there.

Some infos about my setup:
SonarQube Version: 7.9.3.33349
TFVC SCM Provider for SonarQube: 2.3.0
TFS Server V15.117.27414.0

**Comment by lg2de** [comment]
Could you please provide a step-by-step list to reproduce the (your) issue?
Then I can try optimize the code.

**Comment by StefanAdel** [comment]
Yes, of course. I'll try to reproduce it once more on my system to give you a 100% waterproof step-by-step list. I'll need some time to do this. Therefore please expect this list in approx. one week.

**Comment by StefanAdel** [comment]
Hi Lukas,

I'm feeling a little bit stupid, but after retrying after this year it worked as it should. So I don't really know what happend. Either way I did something completely wrong one year ago or maybe the changes in the TFS version had some impact. Anyway it's ok and there's no wrong behaviour anymore. Thank you so much for your support!
