### ISSUE TITLE
ERROR: SCM-TFVC: Unable to annotate the project. Exception: 'TF31002: Unable to connect to this Azure DevOps Server: https://dev.azure.com/example

### ISSUE THREAD

**Issue by rajagspann** [lg2de/sonar-scm-tfvc#66]
Hi Team,

When we ran SonarQube scan for source code which is available on TFS, we encountered the below error:

ERROR: SCM-TFVC: Unable to annotate the project. Exception: 'TF31002: Unable to connect to this Azure DevOps Server: https://dev.azure.com/example.

SonarQube version: version 8.6.1
Installed TFVC Plugin: TFVC 2.3.1 (build 115)

Please let us know what could be the issue?

As per below screen print, does that means TFVC 2.3.1 plugin supports only SonarQube versions b/w 7.9 - 8.2 only?

If yes, is there any alternate solution for the same.?

![image](https://user-images.githubusercontent.com/82435616/125829551-87c58b2f-b836-4211-96bf-932cf54ff158.png)

Raja,

**Comment by rajagspann** [comment]
Hi Support team,

Could someone help us on above.

Raja

**Comment by rajagspann** [comment]
Hi Team,

Any updates on above issue.

Regards,
Raja

**Comment by azharbroadpeak** [comment]
Hi TFVC team,
I am facing the same issue. Annotation was working just fine with-out any issue and then all of sudden it started again for all projects. 
here is the version of sonarquebe that we are using.
![image](https://user-images.githubusercontent.com/48979387/129080573-118939da-aca2-4742-975f-955631b4e223.png)
TFVCTFVC SCM Provider for SonarQube | 2.3.1 (build 115)installed

![Sonar-annotationworking snap](https://user-images.githubusercontent.com/48979387/129079555-955de5a8-6877-42cc-b213-138ec8b7dec2.PNG)
![image](https://user-images.githubusercontent.com/48979387/129079694-a746a709-736b-4d3f-add4-d31b138ede69.png)

Log file is attached.
[log_8_14777.zip](https://github.com/lg2de/sonar-scm-tfvc/files/6970465/log_8_14777.zip)

**Comment by lg2de** [comment]
Hey @rajagspann. There is no team. This is just me...

We are using this plugin with SQ 8.9.1 without known issues. But we are using standalone DevOps server. You are using DevOps services, right? I've never done that before for myself.
So far, I do not see a difference.

Are you sure that you do not have an authentication issue?
https://docs.microsoft.com/en-us/azure/devops/organizations/projects/tf31002-unable-connect-tfs?view=azure-devops

**Comment by JackCrissey** [comment]
Hey @lg2de,
I am getting the same issue as above. I have pointed it to the correct project path and added a custom PAT token, but have had no luck with it connecting. I have also tried providing my credentials that I know work to access the project with zero luck. Do I need to target just the project or the explicit repo containing the project.

**Comment by lg2de** [comment]
Are you using DevOps Services or DevOps Server (on premises)?
I only have experiences with the on-premises version. There I've created a PAT with the following options:
* Code (Full)
* Identity (Read & manage)

Please verify which options you have assigned to you PAT.

You should not "target" the project not the repo. Instead the configuration expects URI of the Project Collection. (In DevOps Services this may be called "Organization".)

**Comment by JackCrissey** [comment]
> Are you using DevOps Services or DevOps Server (on premises)?
> I only have experiences with the on-premises version. There I've created a PAT with the following options:
> 
> * Code (Full)
> * Identity (Read & manage)
> 
> Please verify which options you have assigned to you PAT.
> 
> You should not "target" the project not the repo. Instead the configuration expects URI of the Project Collection. (In DevOps Services this may be called "Organization".)

Removing the Project name resolved this issue however we are now running into the same issue as brought up in issue #40. We are using DevOps Services, so that could be causing it. However I have no clue what it means exactly by it not being mapped in a TFS workspace.

**Comment by lg2de** [comment]
Ok, so I'll close this issue because it seems to be a configuration issue.

Issue 40 is already closed. So please open new issue for the new problem with all details, logs, etc.
