### ISSUE TITLE
tfvc with Sonar 8.9 and later

### ISSUE THREAD

**Issue by MagnusTim** [lg2de/sonar-scm-tfvc#69]
Hi,

I am trying to use this plugin with Sonar 8.9 but can't get it to work, is this project active?

Thanks

Magnus

**Comment by lg2de** [comment]
What means active?
We are using this plugin with version 8.9.1 without known issues.
What problem do you have?

**Comment by MagnusTim** [comment]
Thanks, I will try again. 

With Active I mean if someone is taking care of the plugin, I guess so, right?

**Comment by lg2de** [comment]
I did not develop this plugin. I took the ownership after SonarSource stopped development.
I'll give my best to answer questions and to fix reproducible bugs.

I'll close this issue. Please update if you have more details.
