### ISSUE TITLE
"sonar.tfvc.pat.secured" property return empty value when accessed from our plug-in code in latest Sonar 9.2.4 upgrade

### ISSUE THREAD

**Issue by Syed-Shahul-Hameed** [lg2de/sonar-scm-tfvc#71]
Hi Team,
We have an API call from our plug-in code which uses Personal Access Token. We used to make API call by providing value in "sonar.tfvc.pat.secured" property(till Sonar 8.9.6 version) . From Sonar 9.2.4 upgrade, "sonar.tfvc.pat.secured" property return empty value even after providing correct value in "sonar.tfvc.pat.secured" . Can you help us in accessing this value.
![PAT access issue](https://user-images.githubusercontent.com/98955330/152340219-52c2a864-f89d-4177-ab4e-40dfd00b626c.jpg)

**Comment by lg2de** [comment]
Recently I updated my own system to SonarQube 9.3.0. I did not see an issue with the PAT.

Are you asking because of your own plugin?
Or did you faced a problem with sonar-scm-tfvc?
